# 暂时不知道为什么，但所有字段和结构属性开头都请大写
Redis:
  Addr: 121.40.150.207
  Port: 6379
  Password: redis
  DB: 0
Token:
  # 令牌有效期（默认30分钟
  ExpireTime: 30

MySQL:
  Host: 121.40.150.207
  User: root
  Port: 3306
  Password: root
  DBName: tiktok